import { chromium } from 'playwright';
import { fileURLToPath } from 'url';
import path from 'path';
const TOOLS = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const REPO = path.dirname(TOOLS);
const OUT = path.join(TOOLS, 'verify', 'out') + '/';
import fs from 'fs';
const S=TOOLS;
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const ctx = await b.newContext();
await ctx.route('https://fonts.googleapis.com/**', r => r.fulfill({ status:200, contentType:'text/css', body: fs.readFileSync(S+'/fonts/fonts.css','utf8') }));
await ctx.route('**/pwfonts/*', r => { const f=r.request().url().split('/').pop(); r.fulfill({ status:200, contentType:'font/woff2', body: fs.readFileSync(S+'/fonts/'+f) }); });
const p = await ctx.newPage();
await p.goto('http://127.0.0.1:8765/resume-pdf.html', { waitUntil:'networkidle' });
await p.evaluate(() => document.fonts.ready); await p.waitForTimeout(500);
const m = await p.evaluate(() => { const page=document.querySelector('.page'); const grid=document.querySelector('.content-grid'); const r=grid.getBoundingClientRect(); const main=document.querySelector('.main-column').getBoundingClientRect(); const side=document.querySelector('.side-column').getBoundingClientRect(); return { pageH: page.clientHeight, contentBottom: Math.round(Math.max(main.bottom, side.bottom)), pageBottom: Math.round(page.getBoundingClientRect().bottom), pad: getComputedStyle(page).paddingBottom }; });
console.log('layout', JSON.stringify(m));
await p.pdf({ path: '${REPO}/assets/Jason_Obawemimo_Resume_2026.pdf', format: 'Letter', printBackground: true, margin: { top:0, right:0, bottom:0, left:0 }, preferCSSPageSize: true });
await p.screenshot({ path: S+'/v2/resume.png', fullPage: true });
await b.close();
