// regenerated by scratchpad/vsl/make_data.py after the voice render
export const LEAD_IN = 54;
export const TAIL = 84;
export const LINES = [
  {
    "id": "v1",
    "face": "calm",
    "frames": 187,
    "text": "If you run a lot in Texas and your deals still go to the county on a prayer, give me ninety seconds."
  },
  {
    "id": "v2",
    "face": "warm",
    "frames": 207,
    "text": "I'm Jason. I co-own Triple J Auto Investment in Houston. Every packet we file, I've had a hand in."
  },
  {
    "id": "v3",
    "face": "serious",
    "frames": 206,
    "text": "The county doesn't return a deal because you're bad at this. It returns it because one line on one form didn't agree with another."
  },
  {
    "id": "v4",
    "face": "attentive",
    "frames": 270,
    "text": "So I built Apohenia. Deal Packet Checker reads the deal jacket against what webDEALER wants right now, and hands your clerk a short list before anything leaves the building."
  },
  {
    "id": "v5",
    "face": "serious",
    "frames": 242,
    "text": "It doesn't file for you. It doesn't promise approvals. It reports what it finds, by how often it shows up, and a human decides."
  },
  {
    "id": "v6",
    "face": "calm",
    "frames": 195,
    "text": "We're running it on our own lot first. A few Texas pilot places are open for stores under thirty deals a month."
  },
  {
    "id": "v7",
    "face": "warm",
    "frames": 246,
    "text": "If that's you, pick a time below. Thirty minutes, me, no pitch deck. Bring your last returned packet and we'll look at it together."
  }
];
