import os
TOOLS = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REPO = os.path.dirname(TOOLS)
import json, soundfile as sf, shutil, os
S=TOOLS
lines=json.load(open(S+'/vsl/lines.json')); FPS=30; out=[]; vtt=["WEBVTT",""]; t=54/FPS
def ts(x): return "%02d:%02d:%06.3f"%(int(x//3600),int(x%3600//60),x%60)
for l in lines:
    d,sr=sf.read(S+'/vsl/out_'+l['id']+'.wav'); sec=len(d)/sr; frames=int(round((sec+0.55)*FPS))
    out.append({"id":l['id'],"face":l['face'],"frames":frames,"text":l['text']})
    vtt+= [ts(t)+" --> "+ts(t+sec), l['text'], ""]; t+=frames/FPS
    shutil.copy(S+'/vsl/'+l['id']+'.mp3', S+'/film/public/vsl/'+l['id']+'.mp3')
src="// regenerated by tools/vsl/make_data.py after the voice render\nexport const LEAD_IN = 54;\nexport const TAIL = 84;\nexport const LINES = "+json.dumps(out,indent=2)+";\n"
open(S+'/film/src/vsl-data.ts','w').write(src)
open(REPO+'/assets/film/vsl.vtt','w').write("\n".join(vtt))
print("total frames", 54+84+sum(o['frames'] for o in out), "seconds", (54+84+sum(o['frames'] for o in out))/FPS)
