"""Build SFZ instruments from the CC0 VSCO-2-CE and VCSL sample folders (which
ship as WAVs named by note), plus a wrapper for the Salamander Grand Piano.

Every sample is measured before it is mapped:
  * root pitch: harmonic-sum f0 estimate; the octave convention of each
    library is confirmed by pitchcheck.py and per-sample tuning error is
    corrected with tune= when the estimate is confident (|err| < 40 cents)
  * leading silence trimmed with offset= (onset at -50 dB re peak, minus 2 ms)
  * perceived attack delay (onset -> -6 dB of the early sustain level) is
    written to instruments.json so the composer can pull notes early
  * for crescendo one-shots, the time of the climax is stored likewise
"""
import os, re, glob, json, sys
import numpy as np, soundfile as sf
from scipy import signal

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from pitchcheck import f0_estimate
import audiolib as A
SR_ = A.SR

SRC = os.path.join(A.ROOT, 'src')
V2 = os.path.join(SRC, 'vsco2')
VC = os.path.join(SRC, 'vcsl')
SAL = os.path.join(A.ROOT, 'dl', 'salamander', 'SalamanderGrandPiano-SFZ+FLAC-V3+20200602')
META = {}

NOTE = {'C': 0, 'D': 2, 'E': 4, 'F': 5, 'G': 7, 'A': 9, 'B': 11}


def parse_note(name, octave_shift):
    m = re.search(r'(?<![A-Za-z])([A-G])(#|b)?(-?\d)(?!\d)', name)
    n = NOTE[m.group(1)] + {'#': 1, 'b': -1, None: 0}[m.group(2)]
    return 12 * (int(m.group(3)) + 1 + octave_shift) + n


def analyse(path, expect_midi=None, measure_pitch=True, skip=0.25):
    x, sr = sf.read(path, always_2d=True)
    mono = x.mean(1)
    pk = np.abs(mono).max() + 1e-12
    env = np.abs(mono)
    on = int(np.argmax(env > pk * 10 ** (-50 / 20)))
    off = max(0, on - int(0.002 * sr))
    # smoothed RMS envelope (10 ms)
    w = int(0.01 * sr)
    rms = np.sqrt(np.convolve(mono ** 2, np.ones(w) / w, mode='same'))
    early = rms[on + int(0.3 * sr):on + int(1.2 * sr)]
    sus = np.median(early) if len(early) else rms.max()
    reach = np.argmax(rms[on:] > sus * 0.5)
    attack = reach / sr
    peak_t = (np.argmax(rms) - on) / sr
    tune = 0
    if measure_pitch and expect_midi is not None:
        # energy centroid of partials 1-3 (each within +-50 cents of its
        # expected frequency), over 1 s windows after the attack: robust to
        # vibrato and ensemble spread, unlike a single FFT peak
        f0 = 440 * 2 ** ((expect_midi - 69) / 12)
        ests, wts = [], []
        a0 = on + int(max(0.05, attack + 0.15) * sr)
        for k in range(3):
            seg = mono[a0 + k * int(0.7 * sr):a0 + k * int(0.7 * sr) + int(1.0 * sr)]
            if len(seg) < 0.25 * sr:
                break
            N = 1 << 18
            X = np.abs(np.fft.rfft(seg * np.hanning(len(seg)), N)) ** 2
            fr = np.fft.rfftfreq(N, 1 / sr)
            tot = X.max()
            for h in (1, 2, 3):
                sel = (fr > f0 * h * 2 ** (-0.5 / 12)) & (fr < f0 * h * 2 ** (0.5 / 12))
                if tot <= 0 or not sel.any() or X[sel].max() < tot * 1e-3:
                    continue
                c = (X[sel] * fr[sel]).sum() / X[sel].sum()
                ests.append(1200 * np.log2(c / (f0 * h)))
                wts.append(X[sel].sum())
        if ests:
            o = np.argsort(ests)
            cw = np.cumsum(np.array(wts)[o])
            err = np.array(ests)[o][np.searchsorted(cw, cw[-1] / 2)]
            if 3 <= abs(err) < 45:
                tune = int(round(-err))
    return {'offset': off, 'attack': attack, 'peak_t': peak_t, 'len': (len(mono) - off) / sr,
            'tune': tune, 'sr': sr, 'peak': float(pk)}


def keyranges(roots, lo_ext=5, hi_ext=5):
    roots = sorted(set(roots))
    out = {}
    for i, r in enumerate(roots):
        lo = roots[i - 1] + (r - roots[i - 1]) // 2 + 1 if i > 0 else r - lo_ext
        hi = r + (roots[i + 1] - r) // 2 if i < len(roots) - 1 else r + hi_ext
        out[r] = (max(0, lo), min(127, hi))
    return out


def write_sfz(name, header, regions, meta):
    path = os.path.join(A.SFZ_DIR, name + '.sfz')
    with open(path, 'w') as f:
        f.write('// generated by sfzgen.py\n')
        f.write(header + '\n')
        for r in regions:
            f.write('<region> ' + ' '.join('%s=%s' % kv for kv in r.items()) + '\n')
    META[name] = meta
    return path


def layered(name, folder, pattern, layer_of, octave_shift, header, vel_layers, xfade=True,
            measure_pitch=True, extra=None, fixed_roots=None):
    """Generic note-named multisample: layer_of(filename) -> layer index (0 = softest)."""
    files = sorted(glob.glob(os.path.join(folder, pattern)))
    by_layer = {}
    info = {}
    for fn in files:
        b = os.path.basename(fn)
        L = layer_of(b)
        if L is None:
            continue
        midi = fixed_roots[b] if fixed_roots else parse_note(b, octave_shift)
        an = analyse(fn, midi, measure_pitch)
        by_layer.setdefault(L, {}).setdefault(midi, []).append((fn, an))
        info[b] = dict(an, midi=midi, layer=L)
    nl = len(vel_layers)
    regions = []
    for L in sorted(by_layer):
        kr = keyranges(list(by_layer[L].keys()))
        lo_v, hi_v = vel_layers[L]
        for midi, lst in sorted(by_layer[L].items()):
            for k, (fn, an) in enumerate(lst):
                r = {'sample': fn.replace(' ', '\\ ') if False else fn, 'pitch_keycenter': midi,
                     'lokey': kr[midi][0], 'hikey': kr[midi][1], 'offset': an['offset']}
                if an['tune']:
                    r['tune'] = an['tune']
                if xfade and nl > 1:
                    # equal-power velocity crossfade between neighbouring layers
                    if L > 0:
                        r['xfin_lovel'] = vel_layers[L - 1][1] - 12
                        r['xfin_hivel'] = lo_v + 12
                        r['lovel'] = vel_layers[L - 1][1] - 12
                    else:
                        r['lovel'] = 1
                    if L < nl - 1:
                        r['xfout_lovel'] = hi_v - 12
                        r['xfout_hivel'] = vel_layers[L + 1][0] + 12
                        r['hivel'] = vel_layers[L + 1][0] + 12
                    else:
                        r['hivel'] = 127
                else:
                    r['lovel'], r['hivel'] = lo_v, hi_v
                if len(lst) > 1:
                    r['seq_length'] = len(lst)
                    r['seq_position'] = k + 1
                if extra:
                    r.update(extra(os.path.basename(fn), an))
                regions.append(r)
    # sfz sample paths with spaces: sfizz accepts them to end of line only if
    # sample= is the last opcode, so move it last
    regions = [dict([(k, v) for k, v in r.items() if k != 'sample'] + [('sample', r['sample'])]) for r in regions]
    return write_sfz(name, header, regions, info)


def lay(tags):
    def f(b):
        for i, t in enumerate(tags):
            if re.search(t, b):
                return i
        return None
    return f


def build():
    os.makedirs(A.SFZ_DIR, exist_ok=True)
    # ---------------- strings (VSCO-2-CE, names use middle C = C3, so +1 octave)
    S = os.path.join(V2, 'Strings')
    hdr = '<global> ampeg_attack=0.06 ampeg_release=0.9 amp_veltrack=55 volume=6'
    layered('vln', os.path.join(S, 'Violin Section', 'susVib'), '*.wav', lay([r'_v1', r'_v2']), 1, hdr,
            [(1, 80), (81, 127)])
    layered('vla', os.path.join(S, 'Viola Section', 'susvib'), '*.wav', lay([r'_v1_', r'_v2_']), 1, hdr,
            [(1, 80), (81, 127)])
    layered('vc', os.path.join(S, 'Cello Section', 'susvib'), '*.wav', lay([r'_v1_', r'_v3_']), 1, hdr,
            [(1, 80), (81, 127)])
    layered('cb', os.path.join(S, 'Solo Contrabass', 'SusNV'), '*rr1.wav', lay([r'_v1_', r'_v3_']), 1,
            '<global> ampeg_attack=0.05 ampeg_release=0.8 amp_veltrack=50 volume=6', [(1, 80), (81, 127)])
    # tremolo sections (bowed tremolo, for soft shimmering beds)
    hdr_t = '<global> ampeg_attack=0.08 ampeg_release=0.7 amp_veltrack=55 volume=6'
    layered('vln_trem', os.path.join(S, 'Violin Section', 'Trem'), '*.wav', lay([r'_v1', r'_v2']), 1, hdr_t,
            [(1, 80), (81, 127)])
    layered('vla_trem', os.path.join(S, 'Viola Section', 'trem'), '*.wav', lay([r'_v1_', r'_v2_']), 1, hdr_t,
            [(1, 80), (81, 127)])
    layered('vc_trem', os.path.join(S, 'Cello Section', 'trem'), '*.wav', lay([r'_v1_', r'_v2_']), 1, hdr_t,
            [(1, 80), (81, 127)])
    # ---------------- VCSL mallets and colour (also middle C = C3)
    I = os.path.join(VC, 'Idiophones', 'Struck Idiophones')
    layered('vibes', os.path.join(I, 'Vibraphone', 'Soft Mallets'), '*.wav', lay([r'_v1_', r'_v2_']), 1,
            '<global> ampeg_release=1.6 amp_veltrack=70 volume=0', [(1, 80), (81, 127)])
    layered('vibes_short', os.path.join(I, 'Vibraphone', 'Soft Mallets'), '*.wav', lay([r'_v1_', r'_v2_']), 1,
            '<global> ampeg_release=0.45 amp_veltrack=70 volume=0', [(1, 80), (81, 127)])
    layered('vibes_bowed', os.path.join(I, 'Vibraphone', 'Bowed'), '*.wav', lay([r'bowed']), 1,
            '<global> ampeg_attack=0.2 ampeg_release=2.0 amp_veltrack=40 volume=0', [(1, 127)], xfade=False)
    layered('marimba', os.path.join(I, 'Marimba'), '*.wav', lay([r'_soft_', r'_med_', r'_loud_']), 1,
            '<global> ampeg_release=0.5 amp_veltrack=60 volume=0', [(1, 60), (61, 100), (101, 127)])
    layered('chimes', os.path.join(I, 'Hand Chimes'), '*.wav', lay([r'sus_']), 1,
            '<global> ampeg_release=2.5 amp_veltrack=60 volume=-3', [(1, 127)], xfade=False)
    # felt piano: Knight upright, both layers, dark felt-like filter that opens with velocity
    K = os.path.join(VC, 'Chordophones', 'Zithers', 'Upright Piano, Knight', 'Sustains')
    layered('felt', K, 'Player_vl*.wav', lay([r'_vl1_', r'_vl2_']), 1,
            '<global> ampeg_release=0.6 amp_veltrack=70 volume=3 fil_type=lpf_2p cutoff=1500 '
            'fil_veltrack=3000 resonance=0', [(1, 70), (71, 127)])
    # ---------------- percussion kit
    perc_regions = []
    pm = {}
    BD = os.path.join(VC, 'Membranophones', 'Struck Membranophones', 'Bass Drum 2')
    FD = os.path.join(VC, 'Membranophones', 'Struck Membranophones', 'Frame Drum')
    SC = os.path.join(I, 'Suspended Cymbal 1')
    HH = os.path.join(I, 'Hi-Hat Cymbal')
    SH = os.path.join(I, 'Shaker, Small')
    MT = os.path.join(I, 'Mark Trees', 'Legacy')

    def add(key, fn, lovel=1, hivel=127, seq=None, one_shot=False, extra=''):
        an = analyse(fn, measure_pitch=False)
        r = {'key': key, 'lovel': lovel, 'hivel': hivel, 'offset': an['offset']}
        if seq:
            r['seq_length'], r['seq_position'] = seq
        if one_shot:
            r['loop_mode'] = 'one_shot'
        r['sample'] = fn
        perc_regions.append(r)
        pm.setdefault(str(key), []).append(dict(an, file=os.path.basename(fn)))

    # 36 concert bass drum, 4 dynamics x 2 round robins
    add(36, os.path.join(BD, 'bassdrum_hit_pp1.wav'), 1, 40, (2, 1), True)
    add(36, os.path.join(BD, 'bassdrum_hit_pp2.wav'), 1, 40, (2, 2), True)
    add(36, os.path.join(BD, 'bassdrum_hit_mp1.wav'), 41, 75, (2, 1), True)
    add(36, os.path.join(BD, 'bassdrum_hit_mp2.wav'), 41, 75, (2, 2), True)
    add(36, os.path.join(BD, 'bassdrum_hit_mf1.wav'), 76, 105, (2, 1), True)
    add(36, os.path.join(BD, 'bassdrum_hit_mf2.wav'), 76, 105, (2, 2), True)
    add(36, os.path.join(BD, 'bassdrum_hit_f.wav'), 106, 127, None, True)
    # 38 large frame drum, muted (soft "taiko-like" low tom thud); 39 open
    add(38, os.path.join(FD, 'HDrumL_HitMuted_v2_rr1_Sum.wav'), 1, 80, (2, 1), True)
    add(38, os.path.join(FD, 'HDrumL_HitMuted_v2_rr2_Sum.wav'), 1, 80, (2, 2), True)
    add(38, os.path.join(FD, 'HDrumL_HitMuted_v3_rr1_Sum.wav'), 81, 127, (2, 1), True)
    add(38, os.path.join(FD, 'HDrumL_HitMuted_v3_rr2_Sum.wav'), 81, 127, (2, 2), True)
    add(39, os.path.join(FD, 'HDrumL_Hit_v2_rr1_Sum.wav'), 1, 80, (2, 1), True)
    add(39, os.path.join(FD, 'HDrumL_Hit_v2_rr2_Sum.wav'), 1, 80, (2, 2), True)
    add(39, os.path.join(FD, 'HDrumL_Hit_v3_rr1_Sum.wav'), 81, 127, (2, 1), True)
    add(39, os.path.join(FD, 'HDrumL_Hit_v3_rr2_Sum.wav'), 81, 127, (2, 2), True)
    # 42 small shaker, 44 closed hi-hat tip (4 dynamics x 2 rr)
    add(42, os.path.join(SH, 'Mid_ShakerHighFaster_Down_rr1.wav'), 1, 127, (4, 1), True)
    add(42, os.path.join(SH, 'Mid_ShakerHighFaster_Up_rr1.wav'), 1, 127, (4, 2), True)
    add(42, os.path.join(SH, 'Mid_ShakerHighFaster_Down_rr2.wav'), 1, 127, (4, 3), True)
    add(42, os.path.join(SH, 'Mid_ShakerHighFaster_Up_rr2.wav'), 1, 127, (4, 4), True)
    for v, (lo, hi) in zip(range(1, 5), [(1, 45), (46, 75), (76, 100), (101, 127)]):
        for rr in (1, 2):
            add(44, os.path.join(HH, 'HiHat_HitC_v%d_rr%d_Mid.wav' % (v, rr)), lo, hi, (2, rr), True)
    # crescendo one-shots for transitions
    add(49, os.path.join(SC, 'susCymb1_cresc_2s.wav'), one_shot=True)
    add(50, os.path.join(SC, 'susCymb1_cresc_4s.wav'), one_shot=True)
    add(51, os.path.join(SC, 'susCymb1_cresc_7.5s.wav'), one_shot=True)
    add(52, os.path.join(SC, 'susCymb1_cresc_1.5s.wav'), one_shot=True)
    add(53, os.path.join(BD, 'bassdrum_cresc_short.wav'), one_shot=True)
    add(54, os.path.join(BD, 'bassdrum_cresc_med.wav'), one_shot=True)
    add(55, os.path.join(SC, 'susCymb1_bow_13.wav'), one_shot=True)
    add(56, os.path.join(SC, 'susCymb1_hit_pp1.wav'), one_shot=True)
    add(57, os.path.join(MT, 'windchimes_slowAsc1.wav'), one_shot=True)
    add(58, os.path.join(MT, 'windchimes_random.wav'), one_shot=True)
    add(59, os.path.join(MT, 'windchimes_slowDesc1.wav'), one_shot=True)
    regions = [dict([(k, v) for k, v in r.items() if k != 'sample'] + [('sample', r['sample'])]) for r in perc_regions]
    write_sfz('perc', '<global> amp_veltrack=85 ampeg_release=0.3 volume=6', regions, pm)

    # ---------------- Salamander wrapper: absolute sample path, +gain so the
    # 16-bit sfizz_render output uses its range, pedal noise 6 dB quieter
    src = open(os.path.join(SAL, 'SalamanderGrandPianoRetuned-V3+20200602.sfz')).read()
    G = 9.0

    def fix_group(m):
        line = m.group(0)
        v = re.search(r'volume=(-?[\d.]+)', line)
        extra = -6 if 'on_locc64' in line else 0
        if v:
            return line.replace(v.group(0), 'volume=%g' % (float(v.group(1)) + G + extra))
        return line + ' volume=%g' % (G + extra)
    out = re.sub(r'<group>[^\n]*', fix_group, src)
    out = '<control> default_path=%s/\n' % SAL + out
    path = os.path.join(A.SFZ_DIR, 'piano.sfz')
    with open(path, 'w') as f:
        f.write(out)
    # The sample set's bass is stretched 10-20 cents flat. Pull every keycenter
    # up to A3 back toward equal temperament (mean of partials 1 and 2), so the
    # piano's left hand does not beat against the ET contrabass and sub.
    from sampler import Instrument
    inst = Instrument(path)
    corr = {}
    for kc in sorted(set(r['center'] for r in inst.regions if r['trigger'] == 'attack' and r['center'] <= 57)):
        x = inst.render([(0.0, 2.0, kc, 70)], SR_ * 3)
        m = x.mean(1)
        on = int(np.argmax(np.abs(m) > 0.05 * np.abs(m).max()))
        seg = m[on + int(0.3 * SR_):on + int(1.8 * SR_)]
        N = 1 << 19
        X = np.abs(np.fft.rfft(seg * np.hanning(len(seg)), N))
        fr = np.fft.rfftfreq(N, 1 / SR_)
        devs = []
        for h in (1, 2):
            f0 = A.hz(kc) * h
            sel = (fr > f0 * 2 ** (-0.5 / 12)) & (fr < f0 * 2 ** (0.5 / 12))
            devs.append(1200 * np.log2(fr[np.argmax(X * sel)] / f0))
        d = float(np.mean(devs))
        if abs(d) > 4:
            corr[kc] = int(round(-d))

    def fix_region(m):
        line = m.group(0)
        kc = re.search(r'pitch_keycenter=(\d+)', line)
        if not kc or int(kc.group(1)) not in corr:
            return line
        c = corr[int(kc.group(1))]
        t = re.search(r'tune=(-?\d+)', line)
        if t:
            return line.replace(t.group(0), 'tune=%d' % (int(t.group(1)) + c))
        return line.replace('pitch_keycenter=', 'tune=%d pitch_keycenter=' % c, 1)
    out = re.sub(r'<region>[^\n]*', fix_region, out)
    with open(path, 'w') as f:
        f.write(out)
    META['piano'] = {'gain_db': G, 'bass_tune_correction_cents': corr}

    with open(os.path.join(A.SFZ_DIR, 'instruments.json'), 'w') as f:
        json.dump(META, f, indent=1, default=float)


if __name__ == '__main__':
    build()
    for k, v in META.items():
        if k in ('piano', 'perc'):
            continue
        att = [i['attack'] for i in v.values()]
        tunes = [i['tune'] for i in v.values()]
        lens = [i['len'] for i in v.values()]
        print('%-12s n=%3d attack median %.3fs max %.3fs | tune corr |c| median %d max %d | len min %.1fs' % (
            k, len(v), np.median(att), np.max(att), np.median(np.abs(tunes)), np.max(np.abs(tunes)), min(lens)))
    for k, v in META['perc'].items():
        print('perc', k, [(i['file'], round(i['peak_t'], 2), round(i['len'], 1)) for i in v][:3])
